Update publish_release_actions.yml

diff --git a/.github/workflows/publish_release_actions.yml b/.github/workflows/publish_release_actions.yml
--- a/.github/workflows/publish_release_actions.yml
+++ b/.github/workflows/publish_release_actions.yml
@@ -6,47 +6,8 @@ on:
       - main
     tags:
       - v**
-      
-jobs:
-  build-n-publish-docs:
-    name: Build and publish docs to gh-pages branch
-    runs-on: ubuntu-latest
-    if: startsWith(github.ref, 'refs/tags/v')
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python 3.8
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.8
-    - name: Install pipenv
-      run: pip install pipenv
-    - name: Install dependencies with pipenv
-      run: pipenv install --dev
-    - name: Build documentation
-      uses: ammaraskar/sphinx-action@master
-      with:
-        pre-build-command: "apt-get update --allow-releaseinfo-change -y && apt-get install -y git"
-        docs-folder: "docs/"
-    # Publish built docs to gh-pages branch.
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/ComotionLabs/comotion-sdk.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
 
+jobs:
   build:
     name: Build distribution 📦
     runs-on: ubuntu-latest
@@ -65,7 +26,10 @@ jobs:
         run: pip install pipenv
 
       - name: Install dependencies with pipenv
-        run: pipenv install --dev
+        run: pipenv install --dev --deploy
+
+      - name: Run test suite
+        run: pipenv run pytest -v
 
       - name: Build a binary wheel and a source tarball
         run: |
@@ -140,4 +104,45 @@ jobs:
           path: dist/
       - name: Publish distribution 📦 to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
+  
+  build-n-publish-docs:
+          name: Build and publish docs to gh-pages branch
+          runs-on: ubuntu-latest
+          needs:
+            - publish-to-pypi
+          if: startsWith(github.ref, 'refs/tags/v')
+          steps:
+          - uses: actions/checkout@v4
+          - name: Set up Python 3.8
+            uses: actions/setup-python@v5
+            with:
+              python-version: 3.8
+          - name: Install pipenv
+            run: pip install pipenv
+          - name: Install dependencies with pipenv
+            run: pipenv install --dev
+          - name: Build documentation
+            uses: ammaraskar/sphinx-action@master
+            with:
+              pre-build-command: "apt-get update --allow-releaseinfo-change -y && apt-get install -y git"
+              docs-folder: "docs/"
+          # Publish built docs to gh-pages branch.
+          - name: Commit documentation changes
+            run: |
+              git clone https://github.com/ComotionLabs/comotion-sdk.git --branch gh-pages --single-branch gh-pages
+              cp -r docs/build/html/* gh-pages/
+              cd gh-pages
+              touch .nojekyll
+              git config --local user.email "action@github.com"
+              git config --local user.name "GitHub Action"
+              git add .
+              git commit -m "Update documentation" -a || true
+              # The above command will fail if no changes were present, so we ignore
+              # that.
+          - name: Push changes
+            uses: ad-m/github-push-action@master
+            with:
+              branch: gh-pages
+              directory: gh-pages
+              github_token: ${{ secrets.GITHUB_TOKEN }}
 
